language: cpp
dist: trusty

sudo: required

services:
  - docker
  
before_install:
  - docker pull yadoms/build_for_ubuntu
  
script:
  - docker run --name docCon -e MAKE_PACKAGE=true -e YADOMS_BUILD_BRANCH=${YADOMS_BRANCH} yadoms/build_for_ubuntu
  - docker cp docCon:/yadoms/builds/package .
  - ls -al package
